### PR TITLE
Add of the Italian language

### PR DESCRIPTION
**Pull request by Angelk90**
Hi @DamascenoRafael , I added support for the Italian language.

I noticed that the following file was also created: [it.lproj/Main.strings](https://github.com/Angelk90/reminders-menubar/blob/master/reminders-menu-bar/it.lproj/Main.strings)

Trying the program does not know the words, exactly what they mean?

### CODE REVIEW

**Comment by DamascenoRafael** [comment]
Hi, @Angelk90! Thank you for your contribution 🚀 

The Main.strings file is related to the storyboard (in this case it represents the main menu that appear in apps in general with menus like file, edit, view, help etc.). As this app doesn't have a main menu so far this is never displayed.

Please open the project in Xcode; select the Main.storyboard file; open the inspector (menu on the right); and under "Localization" uncheck the Italian option. At the prompt select to remove the file from disk and then click "Remove".

**Comment by Angelk90** [comment]
@DamascenoRafael : Let me know if it's Ok.

**Comment by DamascenoRafael** [comment]
Awesome @Angelk90!

I was testing it here (despite not knowing how to read Italian) and later on I'll make some adjustments to avoid appearing '...' in the app.

I'm just going to ask you one more thing: I noticed that in some strings you translated "Reminders Menu Bar". As this is the name of the app I think it's better to keep the original without translation. Later I'll remove the app's name and put a `%@` to be replaced by the code, that way we can avoid this confusion with the next translations. OK?

The translations that have the app name are:
- aboutRemindersMenuBarWindowTitle
- remindersMenuBarAppAboutDescription
- appNoRemindersAccessAlertMessage
- appNoRemindersAccessAlertDescription (2 times here)

**Comment by Angelk90** [comment]
@DamascenoRafael : Let me know if it's Ok.

**Pull request merged**
