### PR TITLE
Added 3 menu bar icons

### PR DESCRIPTION
**Pull request by Zabriskije**
I've added 3 menu bar icons taken from [SF Symbols](https://developer.apple.com/sf-symbols/).
Quick preview:

icon-reminder-4

icon-reminder-5

icon-small-dot

### CODE REVIEW

**Comment by DamascenoRafael** [comment]
Hi @Zabriskije, thanks for your contribution.

You can change the `var image` property of the enum to something like below:
```
var image: NSImage {
    return NSImage(named: self.rawValue) ?? NSImage(systemSymbolName: self.rawValue, accessibilityDescription: nil)!
}
```
That way, we can remove the svgs extracted from SF Symbols and use the icon names directly.

**Comment by Zabriskije** [comment]
Done. I'm not familiar with Swift, so basically now we can remove `CaseIterable` and everything to the right side of the String value (like ` = "icon-note-1"`, etc.) since we don't need those anymore?

**Comment by DamascenoRafael** [comment]
@Zabriskije no worries.
We can't remove `CaseIterable` because we need it to iterate over the enum cases to show the icon options in the app.
The string value of the new cases you added (like `"icon-small-dot"`) must match the name that exists in SFSymbol, that way the call to `NSImage(systemSymbolName` will load the SFSymbol.
In addition to fixing the string values you can delete the json and svg files you added (the icons will be loaded from SFSymbol without the need for these files).

**Comment by Zabriskije** [comment]
Sorry, I totally misunderstood the last sentence of your previous message (my bad for reading it in a hurry). Thanks for the clarification.
The only one I can't remove is `smalldot`, since I've modified it.

**Pull request merged**
