### PR TITLE
Little change in Spanish localization

### PR DESCRIPTION
**Pull request by zydeico**

### CODE REVIEW

**Comment by DamascenoRafael** [comment]
Thanks for your contribution! 🎉 

I'm definitely not fluent in Spanish, but is this the way other apps commonly present these texts in Spanish? **If so, I see no problem in approving the changes** 😃 
I say this because I think that some translations are not exactly the same between English and Spanish (like launchAtLoginOptionButton), but I believe they have the same meaning.

Another small detail, es-419 refers to "Spanish (Latin America)", as this covers different countries do you think it would be better to use the flag of Spain 🇪🇸 ? Let me know what you think and if it would be appropriate.

Thanks again for taking the time to make this a better app!

**Comment by zydeico** [comment]
Hey! Thanks for review this changes.
Well, this translations changes are based in other apps and Spanish sounds better, I'm from Mexico and this is the better way to present text (Spanish Spain is a little different in some words)

**Comment by DamascenoRafael** [comment]
Great! We can approve the translation changes 😄 

For Brazil there is also a bit of confusion with Portuguese (Brazil) and Portuguese (Portugal), hahaha.

Regarding the flag we can keep it that way and in the future if there are new additions to Spanish we can think about how to present it. Can you change it to "Spanish (Latin America)" just to be clearer?

**Comment by zydeico** [comment]
hahaha no problem, for Brazil you're right, they need Portuguese language and is a little different of Spanish.

Sure, I add the change right now 😄

**Pull request merged**
