### PR TITLE
Updating Spanish Latin America translations

### PR DESCRIPTION
**Pull request by zydeico**
By the issue #66 I update some localizables to **Spanish Latin America** @DamascenoRafael

### CODE REVIEW

**Comment by DamascenoRafael** [comment]
Awesome @zydeico! Thanks 🎉 

Two small questions:
1 - In the option to enable or disable the shortcut should be "atajo" because it is singular or is "atajos" correct?
2 - Would it be possible to use a shorter text in the "Restore default" button or would it look weird in Spanish? The button restores the shortcut to ⌥⌘R. I can try to adapt the button if necessary.

image

**Comment by zydeico** [comment]
U welcome 😄

Well, is more the Spanish interpretation and the singularity, using "atajo" is for indícate only 1 shortcut and using "atajos" is for multiple shortcuts. I can change the word to "atajos" in the tittle of this window and sounds good too

And for the 2 answer, yes of course, I doing this changes and sounds better "Restaurar ajustes predeterminados" and their translation is "Restore defaults" 

Spanish have too many interpretations hahaha 😂

**Comment by DamascenoRafael** [comment]
@zydeico great!! I'm going to prepare the button to be able to have a larger text if provided :)

The enable and disable toggle is referring to only one shortcut (which will open the app), that's why I asked.

**Comment by zydeico** [comment]
Hey! @DamascenoRafael I updated the changes in Localizables, you can see in the commit [3f5e5bf](https://github.com/DamascenoRafael/reminders-menubar/pull/73/commits/3f5e5bf43e8508c39e547854d870a46054202f92) I attached some screenshots:
[3f5e5bf](https://github.com/DamascenoRafael/reminders-menubar/pull/73/commits/3f5e5bf43e8508c39e547854d870a46054202f92)

Preferencias de los atajos


Iniciar automáticamente



PD: This changes does a better pronunciation an make more sense 😄

**Comment by zydeico** [comment]
Also, I update window height size
image

**Comment by DamascenoRafael** [comment]
Great!! Thanks @zydeico 🚀

**Pull request merged**
