### PR TITLE
Solving issue #27 edit reminder when tap on text

### PR DESCRIPTION
**Pull request by zydeico**
Hi @DamascenoRafael I solved the issue #27, now is possible edit reminders when you tap in text of the reminder 😄 
I attached a video to show the functionality 

https://user-images.githubusercontent.com/6290292/196830457-140daf0a-e106-4a43-be10-397601073ff5.mov

### CODE REVIEW

**Comment by zydeico** [comment]
Hey @DamascenoRafael can u review my PR please 🙏🏻

**Comment by DamascenoRafael** [comment]
Hi @zydeico, thank you for putting effort into this!

1 - I had the opportunity to test this on macOS Monterey, and the TextEditor looks different than it does on macOS Ventura. We would have to try to change this appearance in macOS Monterey or use the TextEditor only in macOS Ventura and later.

Captura de Tela 2022-10-24 às 23 02 19

2 - In your current changes we are changing the state of the reminder, but we are not persisting it in Apple Reminder. We would have to monitor to at some point save the changes.

3 - Just commenting for us to think about how we can integrate the features. I know the current experience (version 1.10.1) for renaming a reminder is not that interesting (a popup to write the new title and click save/cancel). In the next version (1.11.0) we will have a new experience, but it still won't be the same thing as editing directly from the list of reminders.

Screenshot 2022-12-04 at 00 57 57

**Comment by DamascenoRafael** [comment]
Hi @zydeico I will be closing this PR and the related issue.
The new reminder edit popup seems to be working fine and renaming the reminder directly in the list doesn't seem like a necessary addition to me at least at the moment. There will be issues with how it appears in each version of macOS as well as maybe allowing edits by mistake. Please let me know if you have any considerations :)

**Comment by zydeico** [comment]
Hey! @DamascenoRafael 
Thanks for your time, it's perfect for me 😄  have you a nice new year!

**Pull request closed without merging**
