### PR TITLE
French Localization

### PR DESCRIPTION
**Pull request by Piaziker**
Here's the first attempt at a French Localization

### CODE REVIEW

**Comment by DamascenoRafael** [comment]
Thanks for your contribution @Piaziker 🎉

I don't understand French 🤣 , but could you double-check the translation for `newReminderRemoveParsedDateOption`?

More context on this:
This option will be presented as in the image below, and when enabled the date that the user entered as part of the title will be removed from the title when creating the new reminder.
So, for example, if the user types "_do something **tomorrow**_" as a new reminder, the app will automatically add the date referring to "_**tomorrow**_" and if the option is enabled, the new reminder will be created as "_do something_".

Screenshot 2023-03-06 at 20 18 57

**Comment by Piaziker** [comment]
Ok, understood. I have reviewed and adjusted. I also did another pass to make sure the "completed" term was in line with Apple ("terminés" instead of "complétés")

**Comment by DamascenoRafael** [comment]
Great @Piaziker!
Sorry to bother you again about the translation for `newReminderRemoveParsedDateOption`.

Please let me know if this makes sense or if any adjustments are needed.

Using google translate (which could be completely wrong 😆) the French translation appears as:
> "newReminderRemoveParsedDateOption" = "Do not detect date"; (_Ne pas détecter la date_)

whereas the original english text is:
> "newReminderRemoveParsedDateOption" = "Remove parsed date from title";

About the option that this string represents, using the same example I gave earlier,
if the user types "_**do something tomorrow**_" the app behavior will be:

- With the option **enabled**:
The date referring to tomorrow will be suggested and the reminder will be saved as "_do something_".

- With the option **disabled**:
The date referring to tomorrow will be suggested and the reminder will be saved as "_do something tomorrow_".

In both cases the date is recognized and suggested, the only difference is whether the parsed/analyzed date will be removed from the title or not.

Thanks again for the contribution!

**Comment by Piaziker** [comment]
I understand that. I made this choice because I couldn't arrive at something pleasant.
A literal translation would be "Retirer la date détectée dans le titre", which is convoluted. I'm trying something else

**Comment by DamascenoRafael** [comment]
Thanks for the changes and for the effort to add French as a supported language 👏 
It's really not an easy thing to translate, I went through the same thing when translating into Brazilian Portuguese 😆 

I'm accepting this PR now, and in the future if you find it necessary we can update some of the texts.

**Pull request merged**
